<?php
/**
 * @file
 * Provide a simulated beep.
 */
function beep_beep() {
    watchdog('beep', 'Beep!');
}

function beep_beep_action() {
    beep_beep();
}

function bee_multiple_beep_action(){
    beep_beep();
}

/**
*Implemenation of hook_action_info().
*/
function beep_action_info() {
    return array(
        'beep_beep_action' => array(
        'type' => 'system',
        'label' => t('Beep annoyingly'),
        'configurable' => FALSE,
        'triggers' => array('node_view', 'node_insert', 'node_update', 'node_delete'),
        ),
        'beep_multiple_beep_action' => array(
        'type' => 'system',
        'label' => t('Beep multiple times'),
        'configurable' => TRUE,
        'triggers' => array('node_view', 'node_insert', 'node_update', 'node_delete'),
        ),
        );
}