<?php
/**
 * @file
 * Use this module to learn about Drupal's menu system.
 */
 
/**
* Implementation of hook_permission()
*/
function menufun_permission() {
    return array(
        'receive greeting' => array(
        'title' => t('Receive a greeting'),
        'description' => t('Allow users receive a greeting message'),
        ),
    );
}
/**
 * Implementation of hook_menu().
 */
function menufun_menu() {
    $items['menufun'] = array(
        'title' => 'Menu Fun',
        'page callback' => 'menufun_greeting',
        'file' => 'menufun_greeting.inc',
        'page arguments' => array('Jane', 'Doe'),
        'access callback' => 'user_access',
        'access arguments' => array('receive greeting'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => '-1',
        );
    $items['menufun/farewell'] = array(
        'title' => 'Farewell',
        'page callback' => 'menufun_farewell',
        'file' => 'menufun_greeting.inc',
        'access callback' => 'user_access',
        'access arguments' => array('receive greeting'),
        'type' => MENU_NORMAL_ITEM,
        );
    return $items;
}

/**
* Page callback.
*/
function menufun_hello($first_name = '', $last_name = '') {
    return t('Hello @first_name @last_name',
        array('@first_name' => $first_name, '@last_name' => $last_name));
}